site_name: My Docs
theme:
  name: material
  palette:
    primary: deep purple

  features:
    - navigation.expand  
    - content.code.copy
    - navigation.instant
    - navigation.prune: false 
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
  
extra_css:
  - stylesheets/extra.css
  
nav:
  - Table of Contents: index.md
  - '---': []
  - General:
    - Github: gits.md
    - MKDocs Syntax: MKDocs.md
  - '---': []
  - Quectel Yocto:
    - General: SC206E_General_Notes.md
    - Camera - GStreamer: SC206E_GStreamer_Commands.md
    - Yocto - Build: Yocto-build.md
  - '---': []
  - Python:
    - 'Python Virtual Environment': py-venv.md
    - 'Python New Class Template': py-template.md
    - 'Python Decorator Timer Template': py-timer_decorator.md
    